services:
 
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vulnScan
    volumes:
      - pgdata:/var/lib/postgresql/data
 
volumes:
  pgdata: